version: "3.3"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/satya/applications/portainer-config:/data
    restart: always
  
  mariadb:
    image: mariadb:10.11.2
    container_name: mariadb
    ports:
      - '33060:3306'
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - /home/satya/applications/mariadb-data:/var/lib/mysql

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
      - "6700:67/udp"
      - "8000:80/tcp"
    environment:
      TZ: 'United Kingdom/London'
      WEBPASSWORD: 4CaNgAYhsTU!*hbL    
    volumes:
      - '/home/satya/applications/pihole-data/etc-pihole:/etc/pihole'
      - '/home/satya/applications/pihole-data/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: always

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - '8097:8096'
      - '8921:8920'
    volumes:
        - /home/satya/applications/jellyfin-data:/config
    restart: always
  
  emby:
    image: emby/embyserver_arm64v8
    container_name: emby
    ports:
      - '8096:8096'
      - '8920:8920'
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - /home/satya/applications/emby-data:/config
    restart: always