# cxl-enable-region
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cxl-enable-region.1.gz
complete -c cxl-enable-region -s b -l bus
complete -c cxl-enable-region -s d -l decoder
complete -c cxl-enable-region -l debug

