# dconf-editor
# Autogenerated from man page /usr/share/man/man1/dconf-editor.1.gz
complete -c dconf-editor -l I-understand-that-changing-options-can-break-applications -d 'Launches application without showing initial warning'

