# get-edid
# Autogenerated from man page /usr/lib/jvm/default/man/man1/get-edid.1.gz
complete -c get-edid -s b -l bus -d 'only scan the i2c bus BUS (if built with i2c support)'
complete -c get-edid -s c -l classiconly -d 'only use the older VBE interface (if built with i2c and VBE support)'
complete -c get-edid -s h -l help -d 'display a basic help message'
complete -c get-edid -s i -l i2conly -d 'only use the newer i2c interface (if built with i2c and VBE support)'
complete -c get-edid -s m -l monitor -d 'try to return information about monitor number NUM (VBE only)'
complete -c get-edid -s q -l quiet -d 'do not output messages over stderr'

