# git-update-server-info
# Autogenerated from man page /usr/lib/jvm/default/man/man1/git-update-server-info.1.gz
complete -c git-update-server-info -s f -l force -d 'update the info files from scratch'

