# ostree-rev-parse
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ostree-rev-parse.1.gz
complete -c ostree-rev-parse -l single -s S -d 'If the repository has exactly one commit, then print it; any other case will …'

