# snmpdf
# Autogenerated from man page /usr/lib/jvm/default/man/man1/snmpdf.1.gz
complete -c snmpdf -o Cu -d 'Forces the command to use dskTable in mib UCD-SNMP-MIB instead of the default…'
complete -c snmpdf -o Ch -d 'Print sizes in human readable format (i. e.  MiB, GiB, TiB)'

