sudo pacman -R --noconfirm gnome-software-packagekit-plugin
sudo pacman -R --noconfirm gnome-software
sudo pacman -R --noconfirm malcontent
#sudo pacman -R --noconfirm gnome-console
sudo pacman -Runs --noconfirm gnome-photos
sudo pacman -Runs --noconfirm totem
sudo pacman -Runs --noconfirm gnome-weather
sudo pacman -Runs --noconfirm epiphany
sudo pacman -Runs --noconfirm gnome-contacts
sudo pacman -Runs --noconfirm eog
sudo pacman -Runs --noconfirm gnome-maps
sudo pacman -Runs --noconfirm gnome-music
#reinstalling this to fix cache?
sudo pacman -S --noconfirm archlinux-appstream-data
