sudo systemctl enable avahi-daemon
sudo systemctl enable bluetooth
sudo systemctl enable cronie
sudo systemctl enable cups
sudo systemctl enable docker
#sudo systemctl enable emby-server
sudo systemctl enable libvirtd
#sudo systemctl enable portmaster
sudo systemctl enable power-profiles-daemon
sudo systemctl enable supergfxd